name: uniwe
description: "A free, open-source (FOSS) mobile application for HTW Berlin students."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  html: ^0.15.4
  flutter_secure_storage: ^9.0.0
  dynamic_color: ^1.6.8
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  intl: ^0.20.2
  webview_flutter: ^4.13.1
  flutter_displaymode: ^0.7.0
  webview_flutter_android: ^4.11.0
  enough_mail: ^2.1.7

  url_launcher: ^6.3.2
  package_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/icon_foreground.png" 
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_monochrome: "assets/icons/icon_monochrome.png"